config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      get :download
    end
  end
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, uniqueness: true
	validates :description, presence: true

	has_one_attached :image

	def generate_post_pdf
		post_pdf = Prawn::Document.new
		post_pdf.repeat(:all) do
			post_pdf.bounding_box([post_pdf.bounds.left, post_pdf.bounds.top], width: post_pdf.bounds.width) do 
				post_pdf.text 'blog app', size: 40, style: :bold, align: :center
				post_pdf.stroke_horizontal_rule
			end

			post_pdf.bounding_box([post_pdf.bounds.left, post_pdf.bounds.bottom + 30], width: post_pdf.bounds.width) do 
				post_pdf.stroke_horizontal_rule
				post_pdf.move_down 5
				post_pdf.text "Blog App Footer", size: 15, style: :bold, align: :center
			end 


      post_pdf.move_down 30 
  end

  post_pdf.bounding_box([post_pdf.bounds.left, post_pdf.bounds.top - 60], width: post_pdf.bounds.width,height: post_pdf.bounds.height - 100) do
  	post_pdf.font('Times-Roman') do
  		post_pdf.text title, size: 30, style: :bold, align: :center
  	end
  	post_pdf.image StringIO.open(image.download), at: [35,600], width: 500
  	post_pdf.move_down 250
  	post_pdf.text description, line_height: 8
  end
  post_pdf
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy download]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def download
    post_pdf = @post.generate_post_pdf
    if params[:preview].present?
      send_data(post_pdf.render, filename: "#{@post.title}.pdf", type: 'application/pdf', disposition: 'inline')
    else
      send_data(post_pdf.render, filename: "#{@post.title}.pdf", type: 'application/pdf')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :image)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PdfStar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
    <div class="row"> 
    <%= yield %>
  </div>
</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, class: "mt-3" %>
    <%= form.text_field :title, class: "form-control form-control-lg" %>
  </div>

  <div>
    <%= form.label :description, class: "mt-3" %>
    <%= form.text_area :description, class: "form-control form-control-lg", rows: "10" %>
  </div>

  <div>
    <%= form.label :mage, class: "mt-3" %>
    <%= form.file_field :image, class: "form-control form-control-lg" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h1>
    <%= post.title %>
  </h1>

  <% if @post.image.attached? %>
  <%= image_tag @post.image %>
  <% end %>

  <p class= "lead">
    <%= post.description %>
  </p>

</div>

app/views/posts/edit.html.erb
<div class="col-lg-10 mx-auto">
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<div class="col-lg-10 mx-auto">
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>
</div>

app/views/posts/show.html.erb
<div class="col-lg-10 mx-auto">
<p style="color: green"><%= notice %></p>

<%= render @post %>
<%= link_to "Preview and Download as pdf", download_post_path(@post, preview: true), class: "btn btn-danger mt-3 mb-3" %>
<%= link_to "Download as pdf", download_post_path(@post), class: "btn btn-danger mt-3 mb-3" %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Prawn-Pdf</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
    </div>
  </div>
</nav>